### ISSUE TITLE
fail/pause声音不会停止

### ISSUE THREAD

**Issue by arily** [zzhouhe/AsioHookForOsu#3]
retry之后会一直放着

**Comment by XTXTMTXTX** [comment]
这个貌似得去掉这两个音效了 因为这个东西是单次触发就一直放下去的
或者多hook一个bass的函数 stop channel的时候也发回到主程序

**Comment by arily** [comment]
如果issue #1 的问题可以解决我觉得大可以让osu自己放这些与延迟无关的音效。
不过去掉这两个音效包括有可能的话之后修掉我觉得也是完全没问题！

**Comment by XTXTMTXTX** [comment]
与延迟无关的音效在判定上稍微有点麻烦 建议是把效果音效关零
fail/pause 声音不会停止的问题我在重构的版本中修复了，也许你可以看看？[这里](https://github.com/XTXTMTXTX/osu-External-ASIO-Sound)
不过有一个已知问题就是我懒得弄音效音量了 因为这样游戏中效果音效关掉之后外置音效也会被关掉 开起来又会有重声
